version: '2.3'
services:
  database:
    build:
      context: database/postgres
      dockerfile: Dockerfile
    restart: always
    expose:
    - 5432
    volumes:
    - ./database/db_data/:/var/lib/postgresql/data/
    env_file:
    - .env


  migration:
    build:
      context: database/migrations
      dockerfile: Dockerfile
    env_file: .env
    links:
    - database
    depends_on:
    - database
    command: alembic upgrade head
    volumes:
    - ./app/app/schema.py:/migrations/schema.py


  redis:
    build:
      context: redis
      dockerfile: Dockerfile
    expose:
    - 6379
    hostname: redis
    volumes:
    - ./redis/redis_data:/data
    restart: always
    env_file:
    - .env


  worker:
    image: csv-queue
    build:
      context: app
      dockerfile: Dockerfile
    scale: 3
    links:
    - redis
    - database
    depends_on:
    - redis
    - database
    env_file:
    - .env
    command: flask rq worker
    restart: always


  client:
    image: csv-queue
    links:
    - redis
    depends_on:
    - worker
    env_file:
    - .env
    ports:
    - 0:5000:5000


  test:
    image: csv-queue
    env_file:
    - .env
    environment:
      APP_SETTINGS: app.config.TestingConfig
      RQ_REDIS_URL:
    depends_on:
    - redis
    - database
    command: flask cov
